apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myapp
  labels:
    app: myapp
  annotations:
    kubernetes.io/ingress.global-static-ip-name: 35.229.128.53
spec:
  rules:
  - host: myapp.example.local
    http:
      paths:
      - backend:
          serviceName: myapp
          servicePort: 80
