resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource
    tag: "1.8"

resources:
- name: repo
  type: git
  source:
    uri: git://github.com/t-torii/concourse-meetup-tokyo-7-demo.git
    branch: master
    paths: [deploy/*]

- name: stage
  type: kubernetes
  source:
    kubeconfig: ((stage-kubeconfig))

jobs:
- name: stage-deploy
  serial: true
  plan:
  - get: repo
    trigger: true
  - put: stage
    params:
      kubectl: apply -f repo/deploy
      wait_until_ready_selector: app=myapp
